### ISSUE TITLE
[WebForm-002] : Unable to scroll the screen horizontally when "Zoom In"

### ISSUE THREAD

**Issue by samicheemagroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-.NET#66]
This issue was originally raised via forum thread:
https://forum.groupdocs.com/t/horizontal-scroll-bar-not-showing-up-when-zoom/5762

When we "Zoom In" the screen, we are unable to find the scroll bar to move the screen horizontally. Please see below screenshot for your further reference.

![unable to scroll horizontally](https://user-images.githubusercontent.com/29034002/36376740-0f39fac2-1596-11e8-91b4-ac34fc46ba32.png)

**Comment by samicheemagroupdocs** [comment]
Any update on this issue ?

**Comment by bobkovalex** [comment]
This issue is obsolete and doesn't reproduce in new examples, please refer to our new examples:
https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-.NET-MVC
https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-.NET-WebForms
https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-Java-Dropwizard
https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-Java-Spring
